version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 50
  ignore:
  - dependency-name: ember-cli
    versions:
    - 3.24.0
    - 3.25.0
    - 3.25.1
    - 3.25.2
    - 3.25.3
    - 3.26.0
  - dependency-name: release-it
    versions:
    - 14.2.2
    - 14.3.0
    - 14.4.0
    - 14.4.1
    - 14.5.0
    - 14.5.1
  - dependency-name: ember-cli-babel
    versions:
    - 7.23.1
    - 7.25.0
    - 7.26.1
    - 7.26.2
    - 7.26.3
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.2
    - 10.2.0
    - 10.3.0
  - dependency-name: ember-source
    versions:
    - 3.24.1
    - 3.25.0
    - 3.25.1
    - 3.25.3
    - 3.26.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.1
    - 5.3.2
    - 5.4.0
    - 5.6.0
    - 5.6.2
    - 5.6.3
    - 5.6.4
    - 5.6.5
    - 5.7.0
  - dependency-name: "@types/ember-data"
    versions:
    - 3.16.10
    - 3.16.11
    - 3.16.12
    - 3.16.9
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.1
    - 4.3.3
  - dependency-name: "@types/ember"
    versions:
    - 3.16.3
    - 3.16.4
  - dependency-name: whatwg-fetch
    versions:
    - 3.5.0
    - 3.6.1
  - dependency-name: ember-data
    versions:
    - 3.24.0
    - 3.25.0
  - dependency-name: "@types/ember__test-helpers"
    versions:
    - 1.7.3
  - dependency-name: ember-cli-typescript
    versions:
    - 4.0.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: broccoli-concat
    versions:
    - 4.2.4
